# Generated by Django 5.1.6 on 2025-05-03 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0012_slot_is_booked_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='representative',
            field=models.ForeignKey(default=1, limit_choices_to={'user_type': 'representative'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
