# Generated by Django 5.1.6 on 2025-05-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0013_booking_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='serviceprice',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='serviceprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='serviceprice',
            name='service_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('advance', 'Advance')], default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='serviceprice',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
