# Generated by Django 5.1.6 on 2025-05-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0014_remove_booking_service_alter_serviceprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rep_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
